# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Budgetctl < Formula
  desc "Budget tracking from your terminal - import bank CSVs, analyze spending"
  homepage "https://github.com/aeon022/budgetctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/budgetctl/releases/download/v0.1.0/budgetctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "42a1a1b37363fa70e1a6dbfe5aaafea663a234e04aacc107d07b9e6b09836f1e"

    define_method(:install) do
      bin.install "budgetctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/budgetctl/releases/download/v0.1.0/budgetctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "e6db4bbacf744b85fbb138b7a7cef8e17ac12d6ac279a4b370f539220f397069"

    define_method(:install) do
      bin.install "budgetctl"
    end
  end

  test do
    system "#{bin}/budgetctl", "version"
  end
end
