# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calctl < Formula
  desc "Calendar management from your terminal - local-first CLI/TUI for Apple Calendar"
  homepage "https://github.com/aeon022/calctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/calctl/releases/download/v0.1.0/calctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "b6c45198b56686f4793ff23314c25d95af94aaa61801e52efd502660f0461850"

    define_method(:install) do
      bin.install "calctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/calctl/releases/download/v0.1.0/calctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "762178a9835ad5e2d57a34b37565e0423da6ab50101acf0976c3bef9c612c160"

    define_method(:install) do
      bin.install "calctl"
    end
  end

  test do
    system "#{bin}/calctl", "version"
  end
end
