# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diaryctl < Formula
  desc "Developer diary - reads git history, AI generates narrative entries"
  homepage "https://github.com/aeon022/diaryctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/diaryctl/releases/download/v0.1.0/diaryctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "44605ca21e168c46139299b6b535bbecd8c48f68b0341f964694feb7b250d61d"

    define_method(:install) do
      bin.install "diaryctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/diaryctl/releases/download/v0.1.0/diaryctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "7c1d96377611949a1273874b285a4d7ffbe365a688bffff32110ed67bbe29c86"

    define_method(:install) do
      bin.install "diaryctl"
    end
  end

  test do
    system "#{bin}/diaryctl", "version"
  end
end
