# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Habctl < Formula
  desc "Habit tracker for the terminal - streaks, AI coaching, MCP tools"
  homepage "https://github.com/aeon022/habctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/habctl/releases/download/v0.1.0/habctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "93342e507f031c2f36008006394aed37ef416de9a42f0814215f9b46a3de10ba"

    define_method(:install) do
      bin.install "habctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/habctl/releases/download/v0.1.0/habctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "3961cd7e46432ba7b16bc371cdfddf6134b08a8fbef70f494fac2731de58de80"

    define_method(:install) do
      bin.install "habctl"
    end
  end

  test do
    system "#{bin}/habctl", "version"
  end
end
