# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailctl < Formula
  desc "Email from your terminal - send and read email from Markdown files"
  homepage "https://github.com/aeon022/mailctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/mailctl/releases/download/v0.1.0/mailctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "f091d9eb4abe2e20f7e1df0e36ce712b64ca560e65a456a51d594eaa4a21b2ed"

    define_method(:install) do
      bin.install "mailctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/mailctl/releases/download/v0.1.0/mailctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "85c797993d1bd70754c6eccecea297fcf96306e289cc6bed93731a959187cdf2"

    define_method(:install) do
      bin.install "mailctl"
    end
  end

  test do
    system "#{bin}/mailctl", "version"
  end
end
