# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notectl < Formula
  desc "Notes from your terminal - write and read Obsidian vault notes"
  homepage "https://github.com/aeon022/notectl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/notectl/releases/download/v0.1.0/notectl_0.1.0_darwin_amd64.tar.gz"
    sha256 "ba5b1b7172828e7e976a51df02155e4a2dd90319354a419736a78039fadd5607"

    define_method(:install) do
      bin.install "notectl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/notectl/releases/download/v0.1.0/notectl_0.1.0_darwin_arm64.tar.gz"
    sha256 "f51629a8677fad2cde75b1a24624684306f4427a4cc93d63f765fbeccd5d8861"

    define_method(:install) do
      bin.install "notectl"
    end
  end

  test do
    system "#{bin}/notectl", "version"
  end
end
