# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskctl < Formula
  desc "Task management from your terminal - syncs with Apple Reminders"
  homepage "https://github.com/aeon022/taskctl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/taskctl/releases/download/v0.1.0/taskctl_0.1.0_darwin_amd64.tar.gz"
    sha256 "8dffaf5f888b784e5477b3ca311475adee1e11aaee75b299058332e8e005a877"

    define_method(:install) do
      bin.install "taskctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/taskctl/releases/download/v0.1.0/taskctl_0.1.0_darwin_arm64.tar.gz"
    sha256 "6ae5f283e91f37dab092161afa324dc083f9e9056e6194a9e251c190644a01b9"

    define_method(:install) do
      bin.install "taskctl"
    end
  end

  test do
    system "#{bin}/taskctl", "version"
  end
end
