# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timectl < Formula
  desc "Terminal time tracker - start/stop timers, weekly breakdown, MCP server"
  homepage "https://github.com/aeon022/timectl"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aeon022/timectl/releases/download/v0.1.0/timectl_0.1.0_darwin_amd64.tar.gz"
    sha256 "70f9e42bc66b846dc6344dd10d0e0a465cf1ea3d4d04e5e192cb458938e7df7d"

    define_method(:install) do
      bin.install "timectl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aeon022/timectl/releases/download/v0.1.0/timectl_0.1.0_darwin_arm64.tar.gz"
    sha256 "1fcb1e852130e76c0e77bf338139c1f1ef65b9e8950663647408a5c1c04bd209"

    define_method(:install) do
      bin.install "timectl"
    end
  end

  test do
    system "#{bin}/timectl", "version"
  end
end
